<table>
<tr>
<td width=15%><img src="https://www.nitrkl.ac.in/assets/images/logo.png"></img></td>
<td><center><h1>National Institute of Technology
Rourkela, Odisha, India, 769008</h1><h2>Department of Computer Science Engineering</h2></center></td>
</tr>
<tr><td colspan=2><center><h3>Lab-1: Computer Vision Lab</h3></center></br>
            <center><b>(Assignment-4)</b></center></td></tr>
</table>

**122CS0067**

**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [17]:
#Code here
import numpy as np
arr=np.array([10,5,7,20,-9,33],dtype='i4')
print(arr)
print(np.max(arr))
print(np.min(arr))

[10  5  7 20 -9 33]
33
-9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [4]:
#Code here
def find_max(arr):
    max=arr[0]
    for i in range(1,len(arr)):
        if(arr[i]>max):
            max=arr[i]
    return max

arr=np.array(input("Enter a sequence of numbers:").split(),dtype='i4')
print(find_max(arr))

Enter a sequence of numbers:1 2 3 4 5 6 7 8 9
9


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [5]:
#Code here
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[2,4],[6,8]])

print("Sum of arrays:")
print(arr1+arr2)
print("Subtraction of arrays:")
print(arr1-arr2)

Sum of arrays:
[[ 3  6]
 [ 9 12]]
Subtraction of arrays:
[[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [11]:
#Code here
arr1=np.random.rand(5,6)
temp=np.random.rand(1,6)

print(arr1)
print(temp)
print()

arr1=np.vstack([arr1,temp])
print("Stacked Arrays:")
print(arr1)

print("Sum of Rows:")
print(np.sum(arr1,axis=1,keepdims=True))

[[0.80101995 0.15962612 0.91702509 0.39406511 0.92474347 0.67804911]
 [0.41484044 0.80585317 0.44943229 0.89152709 0.89425904 0.13673147]
 [0.71995734 0.56061631 0.36479602 0.69334633 0.86088331 0.73703142]
 [0.26209257 0.66523565 0.30072961 0.89699497 0.14388001 0.92952429]
 [0.33453436 0.50968614 0.36776617 0.02701947 0.78711749 0.2891583 ]]
[[0.89036046 0.75766903 0.48879639 0.32686625 0.53098173 0.60507645]]

Stacked Arrays:
[[0.80101995 0.15962612 0.91702509 0.39406511 0.92474347 0.67804911]
 [0.41484044 0.80585317 0.44943229 0.89152709 0.89425904 0.13673147]
 [0.71995734 0.56061631 0.36479602 0.69334633 0.86088331 0.73703142]
 [0.26209257 0.66523565 0.30072961 0.89699497 0.14388001 0.92952429]
 [0.33453436 0.50968614 0.36776617 0.02701947 0.78711749 0.2891583 ]
 [0.89036046 0.75766903 0.48879639 0.32686625 0.53098173 0.60507645]]
Sum of Rows:
[[3.87452886]
 [3.5926435 ]
 [3.93663072]
 [3.19845711]
 [2.31528193]
 [3.59975031]]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [13]:
#Code here
arr1=np.random.rand(5,6)
temp=np.random.rand(5,1)

print(arr1)
print(temp)
print()

arr1=np.hstack([arr1,temp])
print("Stacked Arrays(Adding Column):")
print(arr1)

print("Sine of each element:")
print(np.sin(arr1))


[[0.61300304 0.95604866 0.28943806 0.38520066 0.58287204 0.63831513]
 [0.42711313 0.64319248 0.11416293 0.78703459 0.18067443 0.55348803]
 [0.08957196 0.72970765 0.07278833 0.38310447 0.48247649 0.39887899]
 [0.21768079 0.50619751 0.20794264 0.24792815 0.17339226 0.1358341 ]
 [0.05656799 0.7541751  0.41326292 0.36157031 0.81035469 0.80020225]]
[[0.31680343]
 [0.19418628]
 [0.11210502]
 [0.62522914]
 [0.54364083]]

Stacked Arrays(Adding Column):
[[0.61300304 0.95604866 0.28943806 0.38520066 0.58287204 0.63831513
  0.31680343]
 [0.42711313 0.64319248 0.11416293 0.78703459 0.18067443 0.55348803
  0.19418628]
 [0.08957196 0.72970765 0.07278833 0.38310447 0.48247649 0.39887899
  0.11210502]
 [0.21768079 0.50619751 0.20794264 0.24792815 0.17339226 0.1358341
  0.62522914]
 [0.05656799 0.7541751  0.41326292 0.36157031 0.81035469 0.80020225
  0.54364083]]
Sine of each element:
[[0.57532631 0.81691901 0.2854137  0.3757451  0.55042403 0.59584317
  0.31153066]
 [0.414245   0.59975307 0.1139151  0.

___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [15]:
#Code here

arr1=np.random.randn(5,6)

temp=arr1[2:4,1:4]

print(arr1)

print()

print(temp)

[[-0.91444257 -0.20029582 -0.54476668  1.8411386  -0.34082676 -0.16408852]
 [-1.26085401 -0.76215128 -0.9875403   0.8211795  -1.30541886  1.1861291 ]
 [-0.88382244 -1.30002369 -1.21064744 -1.07049077  2.14253915  0.80815083]
 [-0.43674451 -0.86474471 -1.68848288 -0.93509356 -1.79786079 -0.67437041]
 [ 0.75636154  0.5262816   1.47298724 -0.69820589 -0.32861711  0.74637881]]

[[-1.30002369 -1.21064744 -1.07049077]
 [-0.86474471 -1.68848288 -0.93509356]]


### Great Job!